
services:
  player-service:
    build: ./src/PlayerService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  ship-service:
    build: ./src/ShipService
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  quest-service:
    build: ./src/QuestService
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  faction-service:
    build: ./src/FactionService
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  event-service:
    build: ./src/EventService
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  item-service:
    build: ./src/ItemService
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  location-service:
    build: ./src/LocationService
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - azuresql
  shop-service:
    build: ./src/ShopService
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
    depends_on:
      - rabbitmq
      - azuresql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  azuresql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
